services:
  product-service:
    build:
      context: ./
      dockerfile: ./product-service/dockerfile.dev3
    ports:
      - "8081:8081"
      - "5005:5005"
    volumes:
      - ./product-service:/app/product-service
    develop:
      watch:
        - action: rebuild
          path: ./product-service/target/*-SNAPSHOT.jar
