# Server
server:
  port: 8086

# Database
spring:
  application:
    name: order-service
  # profiles:
  #   active: local # Change to 'docker' when running in Docker
  cloud:
    config:
      import-check:
        enabled: false

# ---
# spring:
#   config:
#     activate:
#       on-profile: docker
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    # host: rabbitmq
    port: 5672

# ---
# spring:
#   config:
#     activate:
#       on-profile: local
#   rabbitmq:
#     host: localhost
#     port: 5672

  datasource:
#    url: jdbc:postgresql://pg-349c31eb-gishan768-629b.e.aivencloud.com:15794/orderdb?sslmode=require
#    username: avnadmin
#    password: AVNS_W5zTqR7lJoTKHHmmmKQ
    url: jdbc:postgresql://ep-dry-snow-a1szex24-pooler.ap-southeast-1.aws.neon.tech/transportdb?sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_l2wurAbES8Cq
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-components: always
      show-details: always
      db:
        enabled: true
  security:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
      # defaultZone: http://eureka-server:8761/eureka