# Server
server:
  port: 8085

# Database
spring:
  application:
    name: auth-service
  cloud:
    config:
      import-check:
        enabled: false
  rabbitmq:
    host: rabbitmq
    port: 5672

#  datasource:
#    url: jdbc:h2:mem:authdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
#    h2:
#      console:
#        enabled: true
#  jpa:
#    database-platform: org.hibernate.dialect.H2Dialect
#    open-in-view: false

  datasource:
    url: jdbc:postgresql://ep-dry-snow-a1szex24-pooler.ap-southeast-1.aws.neon.tech/orderdb?sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_l2wurAbES8Cq
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-components: always
      show-details: always
      db:
        enabled: true
  security:
    enabled: false

# JWT
jwt:
  secret: your256bitsecretyour256bitsecretyour256bitsecret # Generate using: openssl rand -base64 32
  expiration: 86400000 # 24 hours

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka