FROM maven:3.9-eclipse-temurin-24

WORKDIR /app

# You're inside root now because context is "."
COPY pom.xml .
COPY .mvn .mvn
COPY mvnw .
COPY ./product-service/src ./product-service/src
COPY ./product-service/pom.xml ./product-service/pom.xml

WORKDIR /app/product-service

COPY docker-entrypoint.sh ./
ENTRYPOINT ["sh", "./docker-entrypoint.sh"]

