package com.springcloud.entity;

public enum NotificationType {
    ORDER_CONFIRMATION,
    ORDER_STATUS_UPDATE,
    ORDER_SHIPPED,
    ORDER_DELIVERED,
    ORDER_CANCELLED,
    
    PAYMENT_RECEIVED,
    PAYMENT_FAILED,
    PAYMENT_REFUNDED,
    WALLET_UPDATED,
    
    TRANSPORT_ASSIGNED,
    TRANSPORT_PICKED_UP,
    TRANSPORT_IN_TRANSIT,
    TRANSPORT_DELIVERED,
    TRANSPORT_DELAYED,
    
    PRODUCT_LOW_STOCK,
    PRODUCT_OUT_OF_STOCK,
    PRODUCT_RESTOCKED,
    
    USER_REGISTRATION,
    USER_VERIFICATION,
    PASSWORD_RESET,
    ACCOUNT_SUSPENDED,
    
    SYSTEM_MAINTENANCE,
    SYSTEM_UPDATE,
    PROMOTIONAL,
    ANNOUNCEMENT,
    
    CHAT_MESSAGE,
    GENERAL_NOTIFICATION
}