FROM maven:3.9-eclipse-temurin-24

WORKDIR /app

# You're inside root now because context is "."
COPY pom.xml .
COPY .mvn .mvn
COPY mvnw .
COPY ./api-gateway/src ./api-gateway/src
COPY ./api-gateway/pom.xml ./api-gateway/pom.xml

WORKDIR /app/api-gateway

COPY docker-entrypoint.sh ./
ENTRYPOINT ["sh", "./docker-entrypoint.sh"]

