FROM maven:3.9-eclipse-temurin-24

WORKDIR /app

# You're inside root now because context is "."
COPY pom.xml .
COPY .mvn .mvn
COPY mvnw .
COPY ./eureka-server/src ./eureka-server/src
COPY ./eureka-server/pom.xml ./eureka-server/pom.xml

WORKDIR /app/eureka-server

COPY docker-entrypoint.sh ./
ENTRYPOINT ["sh", "./docker-entrypoint.sh"]
