FROM eclipse-temurin:24-jdk-noble

WORKDIR /app

COPY pom.xml /app

# RUN ls -la /app         # Check wrapper files are here

WORKDIR /app/service

# RUN /app/service/mvnw dependency:go-offline -B
CMD ["bash", "-c", "/app/service/mvnw dependency:go-offline -B"]

# No VOLUME here — using bind mount instead

# EXPOSE 8080 5005

ENTRYPOINT ["bash", "-c", "/app/service/mvnw org.springframework.boot:spring-boot-maven-plugin:run"]
# CMD ["sh", "-c", "while true; do sleep 1; done"]