server:
  port: 8080

spring:
  application:
    name: api-gateway
#  main:
#    web-application-type=reactive:

  cloud:
    gateway:
      default-filters:
        - name: AuthenticationFilter
      routes:
#        - id: product-service
#          uri: lb://product-service
#          predicates:
#            - Path=/products/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**,/api/user/**
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/order/**
        - id: crop-listing-service
          uri: lb://crop-listing-service
          predicates:
            - Path=/api/products/**
        - id: waste-service
          uri: lb://waste-service
          predicates:
            - Path=/api/waste/**
        - id: transport-service
          uri: lb://transport-service
          predicates:
            - Path=/api/transport/**
        - id: warehouse-service
          uri: lb://warehouse-service
          predicates:
            - Path=/api/warehouses/**,/api/facilities/**,/api/slots/**,/api/bookings/**
        - id: analytics-service
          uri: lb://analytics-service
          predicates:
            - Path=/api/analytics/**
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payment/**
        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/api/notification/**
        - id: chat-service
          uri: lb://chat-service
          predicates:
            - Path=/api/chat/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - http://localhost:5173
              - http://localhost:5174
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            exposedHeaders:
              - "*"
            allowCredentials: true

  security:
    user:
      name: farmio
      password: farmio

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

jwt:
  secret: your256bitsecretyour256bitsecretyour256bitsecret # Generate using: openssl rand -base64 32
  expiration: 86400000 # 24 hours
