server:
  port: 8080

spring:
  application:
    name: api-gateway
#  main:
#    web-application-type=reactive:

  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/products/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka

jwt:
  secret: your256bitsecretyour256bitsecretyour256bitsecret # Generate using: openssl rand -base64 32
  expiration: 86400000 # 24 hours
