# Server
server:
  port: 8092

# Database
spring:
  application:
    name: chat-service
  cloud:
    config:
      import-check:
        enabled: false
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672

  datasource:
    url: jdbc:postgresql://ep-dry-snow-a1szex24-pooler.ap-southeast-1.aws.neon.tech/orderdb?sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_l2wurAbES8Cq
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-components: always
      show-details: always
      db:
        enabled: true
  security:
    enabled: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}