auth.service.url=http://auth-service:8085/api/user/all-dto
order.service.url=http://order-service:8086/api/order/admin/all
crop-listing.service.url=http://crop-listing-service:8087/api/products/admin/all
waste.service.url=http://waste-service:8095/waste-listings
waste.agents.service.url=http://waste-service:8095/waste-agents

