# Server
server:
  port: 8091

# Database
spring:
  application:
    name: analytic-service
  cloud:
    config:
      import-check:
        enabled: false
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672

  datasource:
    url: jdbc:postgresql://ep-dry-snow-a1szex24-pooler.ap-southeast-1.aws.neon.tech/analyticsdb?sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_l2wurAbES8Cq
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-components: always
      show-details: always
      db:
        enabled: true
  security:
    enabled: false


auth:
  service:
    url: http://auth-service/api/user/all-dto # Endpoint returning UserDTO[] via Eureka name

order:
  service:
    url: http://order-service/api/order/admin/all # Endpoint returning Order[] via Eureka name

warehouse:
  service:
    url: http://warehouse-service/api/warehouse/admin/all # Endpoint returning Warehouse[] via Eureka name

crop-listing:
  service:
    url: http://crop-listing-service/api/products/admin/all # Endpoint returning Product[] via Eureka name

waste:
  service:
    url:
      listings: http://waste-service/waste-listings # Endpoint via Eureka name
      agents: http://waste-service/waste-agents # Endpoint via Eureka name

transport:
  service:
    url: http://transport-service/api/routes # Endpoint via Eureka name

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}