# Server
server:
  port: 8091

# Database
spring:
  application:
    name: analytic-service
  cloud:
    config:
      import-check:
        enabled: false
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672

  datasource:
    url: jdbc:postgresql://ep-dry-snow-a1szex24-pooler.ap-southeast-1.aws.neon.tech/analyticsdb?sslmode=require&channelBinding=require
    username: neondb_owner
    password: npg_l2wurAbES8Cq
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-components: always
      show-details: always
      db:
        enabled: true
  security:
    enabled: false


auth:
  service:
    url: http://auth-service:8085/api/user/all # This is the endpoint that returns UserDTO[]

order:
  service:
    url: http://order-service:8086/api/order/admin/all # This is the endpoint that returns Order[]

crop-listing:
  service:
    url: http://crop-listing-service:8087/api/products/admin/all # This is the endpoint that returns Product[]

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}